TIDAL_USB_MOD_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(TIDAL_USB_MOD_DIR)/hid.c
SRC_USERMOD += $(TIDAL_USB_MOD_DIR)/console.c

CFLAGS_USERMOD += -I$(TIDAL_USB_MOD_DIR)
CEXAMPLE_MOD_DIR := $(USERMOD_DIR)
